### ISSUE TITLE
Post types displayed with checkboxes not displayed

### ISSUE THREAD

**Issue by finnhensner** [bamadesigner/cpt-onomies#1]
When updating to Wordpress 4.x from 3.9.1, cpt-onomies that are displayed as checkboxes will not show up in my custom post type edit view. The problem exists both in 4.0.x and 4.1.

Cpt-onomies that are displayed as select dropdowns works fine.

Have updated to plugin version 1.3.2 with no luck.

WP 3.9.1
![wp_version_3 9 1](https://cloud.githubusercontent.com/assets/1336584/5717668/01808e5a-9b05-11e4-9f5c-5e875b62c7ab.png)

WP 4.x
![wp_version_4 x](https://cloud.githubusercontent.com/assets/1336584/5717671/1ff685d8-9b05-11e4-950e-09d974aa8320.png)

**Comment by bamadesigner** [comment]
Hmm. I'm having trouble recreating the error. I did just commit a change to trunk (and to GitHub) that fixes issues with multiple tax queries but that shouldn't be what's going on here. Will you update your code from what I just committed and see if that helps?

**Comment by finnhensner** [comment]
Hi, thanks for the quick response. I used the latest version in the master branch here and tested with the same result. I'm thinking it either has something to do with the type of display (select vs checkboxes) or that it could be related to the placement in the main edit area rather than the sidebar. Or do you have any other ideas?

**Comment by finnhensner** [comment]
Ok, so I just created some new cpt-onomies for testing purposes and added them to my post type. The result is kind of weird:
- When using checkboxes as the display method, they are not visible
- When using Autocomplete, they work fine (except I can't with this specific project)
- When using dropdowns, the new ones don't work ("No tests are selected" have no options inside) but the old ones do - like in the image in my first comment

![skarmavbild 2015-01-13 kl 21 13 43](https://cloud.githubusercontent.com/assets/1336584/5728250/1ca9acc0-9b69-11e4-836c-fc878c9103bb.png)

I'm confused.

**Comment by bamadesigner** [comment]
Yea. Me too. I had a theory a minute ago that your CPT-onomies might be conflicting with taxonomies of the same name. Basically, let's say at some point in the history of your site you created a regular taxonomy called 'teman', made a few terms and then decided to try CPT-onomies. Because CPT-onomies are stored differently than regular taxonomies, if you didn't delete the 'teman' taxonomy terms before you started creating 'teman' CPT-onomy terms, you can sometimes have issues where no terms show up. Do you think that might be the case?

**Comment by finnhensner** [comment]
Not impossible however unlikely. We started fresh once we had tested some different options inititally. 

I checked and now there aren't any taxonomy terms in the database that could cause any collisions right now anyway. The thing that feels a bit odd is that everything has worked fine up until we tested to upgrade to WP 4.x, and the issues I saw yesterday with the test-cpt-onomies also feels inconsistent. Also, if I rollback to 3.9.x it works again. Have you had any other reports of bugs related to WP4?

**Comment by bamadesigner** [comment]
I've had a few. I've been doing a few tweaks that I've been uploading to trunk on the WordPress repo and to the github repo. Download the updates and let me know if that fixes anything.

Do you have DEBUG turned on anywhere where you can see if any errors are being thrown?

The meta boxes use [get_terms()](http://wpdreamer.com/plugins/cpt-onomies/documentation/get_terms/) to get the term info. Can you try running that function somewhere else to see if its getting the terms so we can rule that out?

**Comment by bamadesigner** [comment]
I'm going to hope/assume this issue has been fixed. Please feel free to create a new ticket if you need more assistance.
