### ISSUE TITLE
CPT-onomies not showing on JSON REST API.

### ISSUE THREAD

**Issue by myuseringithub** [bamadesigner/cpt-onomies#11]
The custom post type taxonomies selected do not show in REST API calls. 
Plugin used - WordPress REST API Version 2 (JSON REST API)  https://wordpress.org/plugins/rest-api/
API request - dentrist.com/wp-json/wp/v2/mcq/5320
Name of CPT as taxonomy - "studyfield"

I had the same problem with ACF (Advanced Custom Fields) plugin, and after a quick search these fixed it: 
Plugin: https://github.com/airesvsg/acf-to-rest-api
Code in function.php: & I added this code to functions.php

```
//* Add show_in_rest for wp-types plugins to show custom post types in Wordpress REST API V2 *//
add_filter( 'wpcf_type', 'add_show_in_rest_func', 10, 2);
function add_show_in_rest_func($data, $post_type) {
    //if(in_array($post_type, $post_types_all)){
        $data['show_in_rest'] = true;
    //}
    return $data;
}
```

As an example, ACF now shows up on both of these API requests:
- dentrist.com/wp-json/acf/v2/mcq/5320
- dentrist.com/wp-json/wp/v2/mcq/5320

My web app depends on your plugin a lot. Please help me fix it.

**Comment by bamadesigner** [comment]
I will look into it. Thanks for the heads up.

**Comment by linkerx** [comment]
hi, any progress width this? can i help u?

**Comment by linkerx** [comment]
i fix it by adding:
`'show_in_rest'                  => true,`
in $cpt_onomy_args to manager.php line 1110.
maybe u can make it optional in each cpt-onomy settings

**Comment by shoetten** [comment]
Hey, could you release a new version including the change suggested by linkerx?
Maybe even without a settings option, as a quick fix. I don't think there are any disadvantages to having the rest api enabled.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
