### ISSUE TITLE
Will CPT-Onomies work on any object type (i.e users)? 

### ISSUE THREAD

**Issue by beatelite** [bamadesigner/cpt-onomies#12]
I know you can register taxonomies for the user object according to : http://justintadlock.com/archives/2011/10/20/custom-user-taxonomies-in-wordpress

However, as I understand it, you can't register the same taxonomy for both users AND post types. It's one or the other. 

What i'm really trying to do is find a way around this limitation. So first; will this plugin register on user objects and second; Do you know if CTP-onomies would allow me to register a taxonomy for both users AND post types?

Any advice is appreciated.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
