### ISSUE TITLE
Page as post's CPT-onomy makes admin filters broken

### ISSUE THREAD

**Issue by Ciantic** [bamadesigner/cpt-onomies#13]
`$cpt_onomies_manager->register_cpt_onomy("page", array("post"), array());`

It works but the filters in the admin list does not, this is because "page" is reserved word, and cannot be used in URL. e.g. `wp-admin/edit.php?page=something` can't be used as filter.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
