### ISSUE TITLE
Fatal error: Call to a member function get_column_info()

### ISSUE THREAD

**Issue by WebEndev** [bamadesigner/cpt-onomies#14]
Hi Rachel,

Awesome plugin!

Any ideas on how to fix this?

`Fatal error: Call to a member function get_column_info() on null in /home/xxxxxxx/public_html/wp-content/plugins/cpt-onomies/admin.php on line 924`

https://wordpress.org/support/topic/possible-plugin-conflict-4?replies=7

Thanks!

**Comment by Daronspence** [comment]
@bamadesigner and @WebEndev I've found this problem as well, specifically on the Media Manager list view at `wp-admin/upload.php?mode=list`

Should be a simple if check for the attachments screen and then bail out with `return;`

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
