### ISSUE TITLE
Disabled Checkboxes

### ISSUE THREAD

**Issue by ariwinokur** [bamadesigner/cpt-onomies#15]
On the WordPress Plugin Repository, Release 1.3.4 has a bug that also occurs with the current master from Github.  When I am creating a new post, the custom taxonomy I created has disabled checkboxes.

**Comment by Ciantic** [comment]
I have this as well...

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
