### ISSUE TITLE
Notice: Undefined property: WP_Error::$term_id

### ISSUE THREAD

**Issue by abi2** [bamadesigner/cpt-onomies#16]
Since upgrading WordPress to 4.6 we're getting this error message:
Notice: Undefined property: WP_Error::$term_id in /wp-includes/post.php on line 5953
Notice: Undefined property: WP_Error::$term_id in /wp-includes/post.php on line 5954

and we're not the only one:
https://wordpress.org/support/topic/error-notice-after-update-to-wordpress-46/

Thanks for your help

**Comment by ithinkdancan** [comment]
@abi2  any update on how to fix this?

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
