### ISSUE TITLE
Hierarchical permalink

### ISSUE THREAD

**Issue by mkbctrl** [bamadesigner/cpt-onomies#17]
@bamadesigner  Love your plugin, it's really helpful. 

Can you tell me if I am able to create nested post permalink structure using your plugin?
I think I am missing something important.

What I am trying to achieve is a structure like this:

Markets > Single market Description > Single market Variants > Single market Variant Description

Now I have the url like this: 

www.example.com/markets/single_market

And when on **single_market** I am choosing Market Variant the url is being rewrited to the following:

www.example.com/single_market_variants/single_market_variant_description

and it's the opposite of what I am trying to achieve, can you please give me some advice?

Here's again what I am looking for:
**www.example.com/markets/single_market/single_market_variants/single_market_variant_description**

Best regards!

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
