### ISSUE TITLE
All CPT-onomy terms being checked on a new CPT-onomy enabled post

### ISSUE THREAD

**Issue by socki03** [bamadesigner/cpt-onomies#18]
After updating to 4.7, we noticed that all the checkboxes for a brand new post were being checked, and were no longer loading correctly, even after publishing with all (or some) of the CPT-onomy terms checked.

**Comment by socki03** [comment]
After doing some testing on this, I think it's an issue with 4.7.

It looks like there are some issues with the wp_terms_checklist function, which may stem from an issue with wp_get_object_terms, which appears to have gotten [an update](https://core.trac.wordpress.org/browser/tags/4.7/src/wp-includes/taxonomy.php#L1846) to try to work with the new WP_Term_Query.  If you return anything except for the default, it returns ALL the terms, even ones that aren't selected.

I created a quick workaround, to explicitly add the array of term ids in into the wp_terms_checklist args array as 'selected_cats', but if they end up fixing it in an upcoming bug fix, this could be a non-issue.

**Comment by pattonwebz** [comment]
Can confirm this is a 4.7 specific issue. Similar issues are seen with the 'most used' section of terms (with all being selected when creating new posts).

Since that section uses `wp_popular_terms_checklist()` it's not quite so simple to work around but both seem related to recent changes supporting the new WP_Term_Query changes.

**Comment by socki03** [comment]
There was a couple memory leaks prior to 4.7 that I can remember, but I don't think I've experienced anything since then.  Best guess is due to the request being made posts using the CPT-onomies not working correctly because of term ID/object ID conflict? Or just the fact that the object itself has changed.

Keep in mind, this is pure conjecture :)

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
