### ISSUE TITLE
Can I use this in a plugin I'm building?

### ISSUE THREAD

**Issue by digisavvy** [bamadesigner/cpt-onomies#2]
Hey there. Love the plugin and what it can do. I'd like to include this as part of a plugin I'm building for a project. Why? Well, I'd like to build a stand-alone plugin and possibly distribute a commercial version of said plugin. I wanted to run that buy you first and get your thoughts.

Good work and thanks.

**Comment by bamadesigner** [comment]
It's an open source plugin distributed under the GPLv2 license so you're free to take it, modify it, and use it however you like. I've spoken with a few other devs who have done the same thing. It'd be cool if you gave me props somehow but I'm not gonna demand that or anything. If you ever have any questions about the code, feel free to message me. Sorry for the delayed response. I've been a little under the weather.

**Comment by digisavvy** [comment]
Thanks so much! I would definitely give credit where it's due. There's just no good core way to do this, at least that I know of. Awesome work here.
