### ISSUE TITLE
Memory leak issue with version 4.7

### ISSUE THREAD

**Issue by asmp3** [bamadesigner/cpt-onomies#21]
Hey Rachel,
Thanks a ton for the great work and support on the plugin thus far.
There seems to be a memory leak issue with the plugin after updating to version 4.7.
Any update on if this is going to be fixed?

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
