### ISSUE TITLE
It's not working on Wordpress 4.7

### ISSUE THREAD

**Issue by rochiporras** [bamadesigner/cpt-onomies#29]
Hi There,

I just try to update the wordpress to last version, and this plugin makes all my wordpress down.

The error that I get is:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in /wp-includes/class-wp-term-query.php on line 517 

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 256 bytes) in /wp-includes/wp-db.php on line 1841 

It's something that is going to be fix?

thanks very much.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
