### ISSUE TITLE
WPML support needed

### ISSUE THREAD

**Issue by ocReaper** [bamadesigner/cpt-onomies#30]
Hi!

We've encountered some errors with the plugin, which left us no other choice, but to use ACF which can also handle the term connections.
* WPML SEO throws error, because it cannot get the alternate urls
* The rewrite rules are strict to the default language. It should add rewrite rules to all languages based on the post type slug (translation).

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
