### ISSUE TITLE
Issue when trying to show terms on post where selected

### ISSUE THREAD

**Issue by samjco** [bamadesigner/cpt-onomies#31]
this works
```php
  $another_postid = 74;
  $cpt_tax_name = 'features';
  $terms = get_the_terms( $another_postid,$cpt_tax_name );
```
This Doesn't

```php
  $current_postid =get_the_ID();
  $cpt_tax_name = 'features';
  $terms = get_the_terms( $current_postid, $cpt_tax_name );
```

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
