### ISSUE TITLE
Inefficient SQL queries get_object_terms, get_terms_count

### ISSUE THREAD

**Issue by Ciantic** [bamadesigner/cpt-onomies#32]
Cpt-onomies queries take massive time to calculate see following image:

![image](https://user-images.githubusercontent.com/64731/34257255-c9b4fc8a-e661-11e7-8e76-a757592d1b7a.png)

They seem to take nearly a second in page load time. There is some issue with caching, which I haven't yet figured out.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
