### ISSUE TITLE
Editing CPT-onomy resets "Restrict User's Capability to Assign Term Relationships" option

### ISSUE THREAD

**Issue by markparnell** [bamadesigner/cpt-onomies#33]
I've created a CPT-onomy CPT and unticked all the roles under "Restrict User's Capability to Assign Term Relationships" so that anyone can assign terms. However every time we go back in to edit the CPT, it automatically ticks Administrator. This is probably a really small fix but it's really frustrating as we have to remember/notice to untick it again each time - and invariably it doesn't happen and we don't realise until we have issues assigning the terms.

It only seems to happen when no roles are ticked - if any are, it ticks the correct ones.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
