### ISSUE TITLE
CPT-onomies search in not case insensitive for a non ASCII characters.

### ISSUE THREAD

**Issue by aleks-linya** [bamadesigner/cpt-onomies#5]
Case insensitive search only works for English if database charset is set to Unicode.
How to test:
1.  Create CPT-onomy related post with non English name like “Тест”
2.  Try to find it with a lowercase string like “тест”, it will not be found.

Problem is in function ajax_meta_box_autocomplete_callback()

``` php
if ( stripos( $this_term->label, $term ) !== false ) {
```

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
