### ISSUE TITLE
CPT-onomies does not work for custom posts with dash in slug

### ISSUE THREAD

**Issue by aleks-linya** [bamadesigner/cpt-onomies#7]
Currently there is no way to use custom post types with “-“ in slug.

How to test:
1.  Create custom post type with “-“ in slug. Like “test-post-type”.
2.  Add at least one published post of this type.
3.  In the CPT-onomies settings attach this custom post to some other post type like “post”.
4.  On the edit page of this post type (“post” in this example) you’ll see message like “There are no %post type plural% selected.”, and no posts to select from.

Problem is in function user_has_term_capabilities() it’s uses regexes like this: “/assign_cpt_onomy_([a-z_]+)_terms/i”
But in register_post_type() in post.php slug sanitized like this:

``` php
$post_type = sanitize_key( $post_type );
```

And sanitize_key() looks like this (comments removed):

``` php
function sanitize_key( $key ) {
    $raw_key = $key;
    $key = strtolower( $key );
    $key = preg_replace( '/[^a-z0-9_\-]/', '', $key );

    return apply_filters( 'sanitize_key', $key, $raw_key );
}
```

Not only it allows numbers and dash by default it’s also passes sanitized key along with raw key value to filters. So it seems to me that in fact one can’t make any assumptions about slug format.

**Comment by daltonrooney** [comment]
Just experienced this as well. Converting my CPT to include an underscore instead of a dash fixed the problem, although I realize that's not a good solution for most users.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
