### ISSUE TITLE
CPT-onomies will break taxonomy queries for terms term_id and term_taxonomy_id of which are not equal

### ISSUE THREAD

**Issue by aleks-linya** [bamadesigner/cpt-onomies#9]
If in “term_taxonomy” table term_taxonomy_id column values is different from term_id values CPT-onomies will add wrong term_taxonomy_id values in taxonomy query (term_id values instead of term_taxonomy_id).

How to test:
1.  Install Wordpress < 4.2 version. I tested 4.0.8 version.
2.  Create tag with slug “parent”
3.  Create category with same slug “parent”. 
4.  Create category with slug “child” and parent “parent”
5.  Assign any post to the “child” category.
6.  Go to the “parent” category archive page. Post assigned to “child” is showing.
7.  Enable CPT-onomies. 
8.  Go to “parent” category archive page again. Post assigned to “child” is not showing.

Even though you should do this in the Wordpress prior to 4.2, after you will update to the newer version this problem will stay because order of term_taxonomy_id column is changed.
This is because prior to 4.2 there are could be taxonomies with multiple terms. https://developer.wordpress.org/plugins/taxonomy/working-with-split-terms-in-wp-4-2/

This is not a problem by itself; problem is in CPT-onomies way of handling taxonomy queries. Values in tax_query[ 'terms' ] treated like term_id’s even though they are (at least some times) are term_taxonomy_id’s.

**Comment by bamadesigner** [comment]
CPT-onomies has been adopted and is being worked on by another developer. If still an issue, please post in the [main WordPress.org Support forum](https://wordpress.org/support/plugin/cpt-onomies) to reach out to them. Thanks!
